Moved elklib-config scripts to src directory, fixed output

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -22,6 +22,44 @@ include $(top_srcdir)/Makefile.sub
 
 AUTOMAKE_OPTIONS = subdir-objects
 
+EXTRA_DIST =
+
+##
+## Place handy configuration tool somewhere in the system
+##
+EXTRA_DIST +=					\
+	elklib-config.in			\
+	elklib-config-arch.in
+
+bin_SCRIPTS = elklib-config elklib-config-@target_cpu@
+
+all-local: elklib-config elklib-config-@target_cpu@
+
+elklib-config: $(srcdir)/elklib-config.in Makefile
+	( rm -f $@ $@.tmp && \
+	   $(do_subst) < $(srcdir)/elklib-config.in > $@.tmp && \
+	   chmod +x $@.tmp && \
+	   chmod a-w $@.tmp && \
+	   mv -f $@.tmp $@ ) || { \
+		 rm -f $@ $@.tmp ; \
+		 exit 1 ; \
+	}
+
+elklib-config-@target_cpu@: $(srcdir)/elklib-config-arch.in Makefile
+	( rm -f $@ $@.tmp && \
+	   $(do_subst) < $(srcdir)/elklib-config-arch.in > $@.tmp && \
+	   chmod +x $@.tmp && \
+	   chmod a-w $@.tmp && \
+	   mv -f $@.tmp $@ ) || { \
+		 rm -f $@ $@.tmp ; \
+		 exit 1 ; \
+	}
+
+CLEANFILES = elklib-config elklib-config-@target_cpu@
+
+##
+## Library sources
+##
 lib_LIBRARIES =
 
 noinst_HEADERS =				\
@@ -148,7 +186,19 @@ libelk_SRCS =					\
 ##
 update-local: Makefile
 
+
+maintainer-check-parameters: Makefile $(bin_PROGRAMS) $(bin_SCRIPTS)
+	for i in $(bin_PROGRAMS) $(bin_SCRIPTS) ; do \
+	        echo @ECHO_N@ "Checking standard parameters for $$i... " ; \
+	        if ( ./$$i -h 2>&1 > /dev/null ) ; then \
+	                echo "@ECHO_T@ok" ; \
+	        else \
+	                echo "@ECHO_T@error" ; \
+	                exit 1 ; \
+	        fi ; \
+	done
+
 maintainer-check-whitespaces: $(libelk_SRCS)
 	$(WHITESPACE_DETECT) $(libelk_SRCS)
 
-maintainer-check-local: Makefile maintainer-check-whitespaces
+maintainer-check-local: Makefile maintainer-check-parameters maintainer-check-whitespaces
